<form id="submit"method="post"action="<?php echo $this->getUrl('hello/index/subscribe'); ?>" >
  <div class="container">
    <h2>Subscribe to our Newsletter</h2>
    
  </div>

 <div class="container">

  <label for="fname">Name</label><br>
  <input type="text" id="name" name="name" value=""><br>
  <label for="lname">Email</label><br>
  <input type="text" id="email" name="email" value=""><br><br>
  <input class="action submit primary" type="submit" value="Subscribe">
  
</div>
</form>


<script>
  require(["jquery"],function($) {
$(document).ready(function() {

            var name = jQuery("input[name='name']").val();
            var email = jQuery("input[name='email']").val();
            var url = "<?php echo $block->getBaseUrl().'hello/index/subscribe' ?>";
       $("#submit").submit(function(){
        jQuery.ajax({
        url: url,
        type: "POST",
        data: {name:name,email:email},
        showLoader: true,
        success: function(response){
            console.log(response.output);
        }
      
    });
    });
});
});
</script>



           

           